language: php

php:
  - 5.5
  - 5.6
  - 7.0


sudo: false

before_install:
  - mysql -uroot -e "CREATE DATABASE test_foler"
  - mysql -uroot test_foler < dump.sql
  - composer self-update

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

script:
  - vendor/bin/phpunit


after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
